### ISSUE TITLE
Refactor backend

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/twin_aydo#288]
- [x] Go-RMB improvenents.
- [x] Add `/api/locations` endpoint to get Yggdrasil addresses.

Start NestJS refactorations:
- [x] Api service: service to connect to external APIs.
  - [x] Test on frontend
- [x] Auth module: controller, service and types are implemented.
  - [x] Test on frontend
- [x] Db service: service for connecting to database (using Redis for now) and create repositories/indexes.
  - [x] Test on frontend
- [x] Encryption service: service used for encryption purposes (signing key-pairs, decoding key-pairs, generating hashes, ...).
  - [x] Test on frontend
- [x] File service: service for handling local system files (read, write and open files).
  - [x] Test on frontend
- [x] Location module: controller, service, dtos, models and types are implemented for handling Yggdrasil addresses and twin connections.
  - [x] Test on frontend
- [x] Store module: contains multiple services for handling persistent storage with Redis. (connections, public and private keys, working on user data now)
  - [x] Test on frontend
  - [x] Broke store module down in seperate smaller modules for better maintenance. 
- [x] User controller: handling user related endpoints. (ex.: getting user data, uploading an avatar, updating user data, ...)
  - [x] Test on frontend
- [x] Contacts module: module for handling user contacts (ex.: getting user contacts, adding a new contact, ...)
  - [x] Test on frontend
 - [x] Blocked Contacts module: module for handling blocked user contacts 
  - [x] Test on frontend
- [x] Message module: module for handling user message
  - [x] Test on frontend
- [x] Posts module: module for handling posts (ex.: getting posts from contacts, adding post, updating post, ...)
  - [x] Test on frontend
- [x] Yggdrasil service: module for handling yggdrasil twin connections
  - [x] Test on frontend
- [x] Chat module: module for handling everything related to chats.
  - [x] Get accepted chats
  - [x] Create new chat using DTO
  - [x] Send new chat event to socket.io
  - [x] Add socketio testing client
  - [x] Create message and contacts entities in Redis
  - [x] Create get contacts endpoint
  - [x] Refactor huge switch statement for handling different message types using the State Design Pattern
  - [x] Implement `handleIncomingMessage`
  - [x] Fix socket.io emit bug
  - [x] Handle different message types
  - [x] Fix group chats
  - [x] Test on frontend
  - [x] Add draft
  - [x] Update encryption
- [x] JWT Module: module for creating and verifying JWTs
- [x] Socket module: module for handling everything related to socket connections.
  - [x] Test on frontend
  - [x] Create different gateways instead of one big gateway
  - [x] Handle realtime status updates
- [x] Files module:
  - [x] Quantum
  - [x] Shares
  - [x] Get file info
  - [x] Files in chat

**Comment by EdwardKerckhof** [comment]
- [x] Go-RMB improvenents.
- [x] Add `/api/locations` endpoint to get Yggdrasil addresses.

Start NestJS refactorations:
- [x] Api service: service to connect to external APIs.
- [x] Auth module: controller, service and types are implemented.
- [x] Db service: service for connecting to database (using Redis for now) and create repositories/indexes.
- [x] Encryption service: service used for encryption purposes (signing key-pairs, decoding key-pairs, generating hashes, ...).
- [x] File service: service for handling local system files (read, write and open files).
- [x] Location module: controller, service, dtos, models and types are implemented for handling Yggdrasil addresses and twin connections.
- [ ] Store module (WIP): contains multiple services for handling persistent storage with Redis. (connections, public and private keys, working on user data now).
- [ ] User controller (WIP): handling user related endpoints. (ex.: getting user data, uploading an avatar, updating user data, ...)
- [ ] Yggdrasil service (WIP): 90% finished, just need to find a way to get yggdrasil peers instead of using hardcoded peers.

**Comment by ken-de-moor** [comment]
14 june deadline

**Comment by ken-de-moor** [comment]
Closing this as we'll verify it by just logging all things seperately.
